In [2]:
import os
# data folder is in the parent folder of the code folder on the level abolve
data_folder_dir = '../data'

In [6]:
import pandas as pd
# read the Store 1 - Items List.csv in the data folder
store1_items_list = pd.read_csv(os.path.join(data_folder_dir, 'Store 1 - Items List.csv'))
# append the store number to the store1_items_list as a column on the left
store1_items_list.insert(0, 'Store', 1)
store1_items_list

In [7]:
# same goes for store 2
store2_items_list = pd.read_csv(os.path.join(data_folder_dir, 'Store 2 - Items List.csv'))
store2_items_list.insert(0, 'Store', 2)
store2_items_list

    Store Business Line           Item Name Abbreviation for Item Name
0       1         Drink              Coffee                       Coff
1       1         Drink               Latte                       Latt
2       1         Drink          Cappuccino                       Capp
3       1         Drink         Iced Coffee                   IcedCoff
4       1         Drink       Hot Chocolate                    HotChoc
..    ...           ...                 ...                        ...
88      1          Food   Coconut Macaroons                   CocoMaca
89      1          Food  Cream Cheese Bagel               CreaCheeBage
90      1          Food    Almond Croissant                   AlmoCroi
91      1          Food      Chocolate Tart                   ChocTart
92      1          Food        Lemon Square                   LemoSqua

[93 rows x 4 columns]